--create tables
CREATE TABLE Vendors(
id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
name VARCHAR(255),
address VARCHAR(1000));

CREATE TABLE Products(
id int GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
vendor_id int NOT NULL,
name VARCHAR(255),
description VARCHAR(10000),
price DECIMAL(10,2),
quantity int,
FOREIGN KEY(vendor_id) REFERENCES Vendors(id));

--insert data

INSERT INTO vendors (name, address) VALUES ('Amazon', 'Seattle, Washington')
INSERT INTO vendors (name, address) VALUES ('eBay', 'San Jose, California')
INSERT INTO vendors (name, address) VALUES ('Newegg', 'City of Industry, California')

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (1, 'Intel i7-7700k', 'Intel® Core™ i7-7700K Processor
8M Cache, up to 4.50 GHz', 350.00, 10)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (1, 'Asus GeForce GTX 1080 Ti', 'ASUS GeForce GTX 1080 Ti 11GB GDDR5X 352bit PCIe (ROG-STRIX-GTX1080TI-O11G-GAMING)', 799.99, 15)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (1, 'Corsair Vengeance DDR4 RAM 16GB', 'Corsair Vengeance LPX 16GB (2x8GB) DDR4 DRAM 3000MHz C15 Desktop Memory Kit - Black (CMK16GX4M2B3000C15)', 204.99, 16)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (1, 'ASUS ROG Maximus X Hero Motherboard', 'ASUS ROG Maximus X Hero (Wi-Fi AC) LGA1151 DDR4 DP HDMI M.2 Z370 ATX Motherboard with onboard 802.11ac WiFi, Gigabit LAN and USB 3.1 for 8th Generation Intel Core Processors', 259.99, 7)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (1, 'Cooler Master V1200 Power Supply', 'Cooler Master V1200 - Fully Modular 1200W 80 PLUS Platinum PSU with Silent Fanless Mode Operation (6th Generation Skylake Ready)', 299.99, 14)



INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (2, 'Intel i7-7700k', 'Intel® Core™ i7-7700K Processor
8M Cache, up to 4.50 GHz', 334.23, 8)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (2, 'Asus GeForce GTX 1080 Ti', 'ASUS GeForce GTX 1080 Ti 11GB GDDR5X 352bit PCIe (ROG-STRIX-GTX1080TI-O11G-GAMING)', 840.29, 20)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (2, 'Kingston HyperX FURY DDR4 RAM 8GB', 'Kingston HyperX FURY Black 8GB Kit (2x4GB) 2133MHz DDR4 Non-ECC CL14 DIMM Desktop Memory (HX421C14FBK2/8)', 199.99, 12)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (2, 'Gigabyte X299 AORUS Gaming 7', 'GIGABYTE X299 AORUS Gaming 7 (Intel LGA 2066 Core i9/ ATX/ 3 M.2/ Front USB 3.1 /ESS Sabre Audio /RGB Fusion/Dual LAN / Killer WIFI /3 Way SLI Motherboard)', 399.99, 25)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (2, 'Cooler Master V1200 Power Supply', 'Cooler Master V1200 - Fully Modular 1200W 80 PLUS Platinum PSU with Silent Fanless Mode Operation (6th Generation Skylake Ready)', 289.99, 30)



INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (3, 'Intel i7-6700k', 'Intel Core i7 6700K 4.00 GHz Unlocked Quad Core Skylake Desktop Processor, Socket LGA 1151 [BX80662I76700K]', 332.79, 11)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (3, 'Asus GeForce GTX 1080 Ti', 'ASUS GeForce GTX 1080 Ti 11GB GDDR5X 352bit PCIe (ROG-STRIX-GTX1080TI-O11G-GAMING)', 800.35, 6)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (3, 'Kingston HyperX FURY DDR4 RAM 8GB', 'Kingston HyperX FURY Black 8GB Kit (2x4GB) 2133MHz DDR4 Non-ECC CL14 DIMM Desktop Memory (HX421C14FBK2/8)', 205.38, 45)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (3, 'Gigabyte X299 AORUS Gaming 7', 'GIGABYTE X299 AORUS Gaming 7 (Intel LGA 2066 Core i9/ ATX/ 3 M.2/ Front USB 3.1 /ESS Sabre Audio /RGB Fusion/Dual LAN / Killer WIFI /3 Way SLI Motherboard)', 381.99, 13)

INSERT INTO products (vendor_id, name, description, price, quantity) VALUES (3, 'EVGA SuperNOVA 850 Platinum 850W', 'EVGA SuperNOVA 850 P2, 80+ PLATINUM 850W , Fully Modular , EVGA ECO Mode, 10 Year Warranty , Includes FREE Power On Self Tester, Power Supply 220-P2-0850-X1', 154.95, 17)